// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chainmail-dashboard/Dashboard.tsx": () => import("../components/mockups/chainmail-dashboard/Dashboard.tsx"),
  "./components/mockups/chainmail-dashboard/DashboardDark.tsx": () => import("../components/mockups/chainmail-dashboard/DashboardDark.tsx"),
  "./components/mockups/chainmail-dashboard/DashboardLight.tsx": () => import("../components/mockups/chainmail-dashboard/DashboardLight.tsx"),
  "./components/mockups/chainmail-landing/LandingDark.tsx": () => import("../components/mockups/chainmail-landing/LandingDark.tsx"),
  "./components/mockups/chainmail-landing/LandingLight.tsx": () => import("../components/mockups/chainmail-landing/LandingLight.tsx")
};
